-- Queries SQL de referencia para o dataset COVID-19 (SQLite)
-- Estas queries sao para exercicio e consulta.
-- O processo de ETL principal esta no script 01_etl.R

-- Selecionar colunas relevantes agrupadas por municipio
SELECT
  NU_NOTIFIC,
  DT_NOTIFIC,
  SG_UF,
  ID_MUNICIP,
  ID_PAIS,
  CS_SEXO,
  NU_IDADE_N,
  FEBRE,
  TOSSE,
  GARGANTA,
  DESC_RESP,
  SATURACAO,
  DIARREIA,
  VOMITO,
  FATOR_RISC,
  CARDIOPATI,
  HEMATOLOGI,
  SIND_DOWN,
  HEPATICA,
  ASMA,
  DIABETES,
  NEUROLOGIC,
  PNEUMOPATI,
  IMUNODEPRE,
  RENAL,
  OBESIDADE,
  DOR_ABD,
  FADIGA,
  PERD_OLFT,
  PERD_PALA,
  VACINA,
  DT_INTERNA,
  UTI,
  RAIOX_RES,
  TOMO_RES,
  AMOSTRA
FROM dados_covid
GROUP BY ID_MUNICIP
ORDER BY SG_UF;

-- Agregacao de sintomas, comorbidades e exames por UF
SELECT
  SG_UF AS UF,
  SUM(FEBRE) AS FEBRE,
  SUM(TOSSE) AS TOSSE,
  SUM(GARGANTA) AS GARGANTA,
  SUM(DESC_RESP) AS RESPIRATORIO,
  SUM(DIARREIA) AS DIARREIA,
  SUM(VOMITO) AS VOMITO,
  SUM(CARDIOPATI) AS CARDIOPATICO,
  SUM(HEMATOLOGI) AS HEMATOLOGICO,
  SUM(SIND_DOWN) AS DOWN,
  SUM(HEPATICA) AS HEPATICA,
  SUM(ASMA) AS ASMA,
  SUM(DIABETES) AS DIABETES,
  SUM(NEUROLOGIC) AS NEUROLOGICO,
  SUM(PNEUMOPATI) AS PNEUMOPATICO,
  SUM(IMUNODEPRE) AS IMUNODEPRE,
  SUM(RENAL) AS RENAL,
  SUM(OBESIDADE) AS OBESIDADE,
  SUM(DOR_ABD) AS DOR_ABD,
  SUM(FADIGA) AS FADIGA,
  SUM(PERD_OLFT) AS PERD_OLFT,
  SUM(PERD_PALA) AS PERD_PALA,
  SUM(UTI) AS UTI,
  SUM(RAIOX_RES) AS RAIOX,
  SUM(TOMO_RES) AS TOMOGRAFIA,
  SUM(AMOSTRA) AS AMOSTRA,
  COUNT(*) AS total_casos
FROM dados_covid
GROUP BY SG_UF
ORDER BY SG_UF, total_casos DESC;

-- Agregacao apenas de comorbidades por UF
SELECT
  SG_UF AS UF,
  SUM(CARDIOPATI) AS CARDIOPATICO,
  SUM(HEMATOLOGI) AS HEMATOLOGICO,
  SUM(SIND_DOWN) AS DOWN,
  SUM(HEPATICA) AS HEPATICA,
  SUM(ASMA) AS ASMA,
  SUM(DIABETES) AS DIABETES,
  SUM(NEUROLOGIC) AS NEUROLOGICO,
  SUM(PNEUMOPATI) AS PNEUMOPATICO,
  SUM(IMUNODEPRE) AS IMUNODEPRE,
  SUM(RENAL) AS RENAL,
  SUM(OBESIDADE) AS OBESIDADE,
  COUNT(*) AS total_casos
FROM dados_covid
GROUP BY SG_UF
ORDER BY SG_UF, total_casos DESC;
